# -*- coding: utf-8 -*-
"""
/***************************************************************************
 StudyAreaGenerator
                                 A QGIS plugin
 This Plugin generates study area for NIAs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-10-21
        copyright            : (C) 2021 by Samiul Choudhury
        email                : samiulhaydereee@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Samiul Choudhury'
__date__ = '2021-10-21'
__copyright__ = '(C) 2021 by Samiul Choudhury'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load StudyAreaGenerator class from file StudyAreaGenerator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .study_area_generator import StudyAreaGeneratorPlugin
    return StudyAreaGeneratorPlugin()
